# Generated by Django 6.0 on 2026-01-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('civil', 'Civil Engineering'), ('auto', 'Automobile Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('ece', 'Electronics & Communication Engineering'), ('ist', 'Information Science & Technology'), ('ice', 'Instrumentation & Control Engineering'), ('mech', 'Mechanical Engineering')], max_length=10)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('uploaded_by', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
