# Generated by Django 6.0 on 2026-01-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_questionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='doc_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('syllabus', 'Syllabus'), ('midterm', 'Midterm Papers'), ('model', 'Model Papers')], default='notes', max_length=20),
        ),
    ]
