# Generated by Django 6.0 on 2026-01-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_questionpaper_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='college',
            field=models.CharField(choices=[('meip', 'MEIP'), ('pvp', 'PVP'), ('sjp', 'SJP'), ('rrp', 'RRP')], default='meip', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=10)),
                ('branch', models.CharField(blank=True, max_length=10, null=True)),
                ('wants_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('email', 'college')},
            },
        ),
    ]
