# Generated by Django 6.0 on 2026-01-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_questionpaper_college_studentnotification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentnotification',
            unique_together=set(),
        ),
    ]
