# Generated by Django 6.0 on 2026-01-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentnotification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotification',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='semester',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
