# Generated by Django 6.0 on 2026-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentnotification_last_viewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('logo_initials', models.CharField(default='CO', max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ist', 'Information Science & Technology'), ('both', 'Both CSE & ISE')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(help_text='Comma-separated skills', max_length=500)),
                ('apply_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
